- name: Check if Helm is installed
  command: helm version --short
  register: helm_check
  ignore_errors: true

- name: Download Helm archive
  get_url:
    url: "https://get.helm.sh/helm-{{ helm_version }}-{{ helm_arch }}.tar.gz"
    dest: "/tmp/helm.tar.gz"
    mode: "0644"
  when: helm_check.rc != 0

- name: Extract Helm
  unarchive:
    src: "/tmp/helm.tar.gz"
    dest: "/tmp"
    remote_src: yes
  when: helm_check.rc != 0

- name: Move Helm binary
  copy:
    src: "/tmp/{{ helm_arch }}/helm"
    dest: "/usr/local/bin/helm"
    mode: "0755"
    remote_src: yes
  when: helm_check.rc != 0

- name: Add VictoriaMetrics Helm repo
  command: helm repo add vm https://victoriametrics.github.io/helm-charts/
  environment:
    KUBECONFIG: "{{ ansible_user_dir }}/.kube/config"
  ignore_errors: true

- name: Add Grafana Helm repo
  command: helm repo add grafana https://grafana.github.io/helm-charts
  ignore_errors: true

- name: Update Helm repos
  command: helm repo update