---
# tasks file for roles/master
- name: Check if Kubernetes is already initialized
  stat:
    path: /etc/kubernetes/admin.conf
  register: kube_init_status

- name: Initialize Kubernetes control plane (if not already initialized)
  command: kubeadm init --pod-network-cidr=192.168.0.0/16
  when: not kube_init_status.stat.exists
  register: kubeadm_init_output

- name: Display kubeadm join command
  debug:
    msg: "{{ kubeadm_init_output.stdout }}"
  when: not kube_init_status.stat.exists

- name: Create .kube directory
  file:
    path: "{{ ansible_user_dir }}/.kube"
    state: directory
    mode: '0755'
  when: not kube_init_status.stat.exists

- name: Copy admin.conf to .kube/config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ ansible_user_dir }}/.kube/config"
    remote_src: yes
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: '0600'
  when: not kube_init_status.stat.exists

- name: Set KUBECONFIG environment variable
  lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    line: 'export KUBECONFIG={{ ansible_user_dir }}/.kube/config'
    create: yes
  when: not kube_init_status.stat.exists

- name: Wait for API server
  command: kubectl get nodes
  environment:
    KUBECONFIG: "{{ ansible_user_dir }}/.kube/config"
  register: api_ready
  retries: 20
  delay: 15
  until: api_ready.rc == 0

- name: Check if Kubernetes is already initialized
  stat:
    path: /etc/cni/net.d/10-calico.conflist
  register: calico_cni_status

- name: Set kubernetes CNI (e.g., Calico)
  set_fact:
    cni_manifest_url: "https://raw.githubusercontent.com/projectcalico/calico/{{ calico_version }}/manifests/calico.yaml"

- name: Ensure manifest directory exists
  file:
    path: "{{ manifest_dir }}"
    state: directory
    mode: "0755"

- name: Download kubernetes CNI manifest
  ansible.builtin.get_url:
    url: "{{ cni_manifest_url }}"
    dest: "{{ manifest_dir }}/calico.yaml"
    mode: '0644'

- name: Apply pod network addon (e.g., Calico)
  command: kubectl apply -f {{ manifest_dir }}/calico.yaml
  environment:
    KUBECONFIG: "{{ ansible_user_dir }}/.kube/config"
  when: not calico_cni_status.stat.exists

- name: Set local-path manifest URL
  set_fact:
    local_path_manifest_url: "https://raw.githubusercontent.com/rancher/local-path-provisioner/{{ local_path_version }}/deploy/local-path-storage.yaml"

- name: Download local-path-storage manifest
  ansible.builtin.get_url:
    url: "{{ local_path_manifest_url }}"
    dest: "{{ manifest_dir }}/local-path-storage.yaml"
    mode: '0644'

- name: Apply local-path-storage manifest
  command: kubectl apply -f {{ manifest_dir }}/local-path-storage.yaml
  environment:
    KUBECONFIG: "{{ ansible_user_dir }}/.kube/config"

- name: Render vmcluster Helm values
  template:
    src: local-path-storage-default.yaml.j2
    dest: "{{ manifest_dir }}/local-path-storage-default.yaml"

- name: Apply manifest local-path-storage-default to Kubernetes
  command: kubectl apply -f {{ manifest_dir }}/local-path-storage-default.yaml
  environment:
    KUBECONFIG: "{{ ansible_user_dir }}/.kube/config"

- name: Enable strictARP in kube-proxy
  shell: |
    kubectl get configmap kube-proxy -n kube-system -o yaml \
    | sed -e "s/strictARP: false/strictARP: true/" \
    | kubectl apply -f - -n kube-system
  environment:
    KUBECONFIG: "{{ ansible_user_dir }}/.kube/config"

- name: Download MetalLB manifest
  get_url:
    url: "https://raw.githubusercontent.com/metallb/metallb/{{ metallb_version }}/config/manifests/metallb-native.yaml"
    dest: "{{ manifest_dir }}/metallb-native.yaml"
    mode: "0644"

- name: Apply MetalLB manifest
  command: kubectl apply -f {{ manifest_dir }}/metallb-native.yaml
  environment:
    KUBECONFIG: "{{ ansible_user_dir }}/.kube/config"

- name: Render MetalLB IPAddressPool manifest
  template:
    src: metallb-ip-pool.yaml.j2
    dest: "{{ manifest_dir }}/metallb-ip-pool.yaml"
    mode: "0644"

- name: Apply MetalLB IPAddressPool
  command: kubectl apply -f {{ manifest_dir }}/metallb-ip-pool.yaml
  environment:
    KUBECONFIG: "{{ ansible_user_dir }}/.kube/config"
  register: metallb_ready
  retries: 20
  delay: 15
  until: metallb_ready.rc == 0

- name: Render MetalLB L2Advertisement manifest
  template:
    src: metallb-l2advert.yaml.j2
    dest: "{{ manifest_dir }}/metallb-l2advert.yaml"

- name: Apply MetalLB L2Advertisement
  command: kubectl apply -f {{ manifest_dir }}/metallb-l2advert.yaml
  environment:
    KUBECONFIG: "{{ ansible_user_dir }}/.kube/config"

- name: Download ingress-nginx manifest
  get_url:
    url: "https://raw.githubusercontent.com/kubernetes/ingress-nginx/{{ ingress_nginx_version }}/deploy/static/provider/cloud/deploy.yaml"
    dest: "{{ manifest_dir }}/ingress-nginx.yaml"
    mode: "0644"

- name: Apply ingress-nginx
  command: kubectl apply -f {{ manifest_dir }}/ingress-nginx.yaml
  environment:
    KUBECONFIG: "{{ ansible_user_dir }}/.kube/config"

- name: Install Helm App
  include_tasks: helm_main.yml